/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Lêdo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_cadastrar = new javax.swing.JMenu();
        menu_cadastrarDono = new javax.swing.JMenuItem();
        menu_cadastrarCliente = new javax.swing.JMenuItem();
        menu_cadastrarImovel = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menu_pesquisarImovel = new javax.swing.JMenuItem();
        menu_pesquisarClienteDono = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 204, 153));
        jDesktopPane1.setForeground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        menu_cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group_add.png"))); // NOI18N
        menu_cadastrar.setText("Cadastrar ");

        menu_cadastrarDono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_add.png"))); // NOI18N
        menu_cadastrarDono.setText("Dono");
        menu_cadastrarDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadastrarDonoActionPerformed(evt);
            }
        });
        menu_cadastrar.add(menu_cadastrarDono);

        menu_cadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_add.png"))); // NOI18N
        menu_cadastrarCliente.setText("Cliente");
        menu_cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadastrarClienteActionPerformed(evt);
            }
        });
        menu_cadastrar.add(menu_cadastrarCliente);

        menu_cadastrarImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/casa1.png"))); // NOI18N
        menu_cadastrarImovel.setText("Imovel");
        menu_cadastrarImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadastrarImovelActionPerformed(evt);
            }
        });
        menu_cadastrar.add(menu_cadastrarImovel);

        jMenuBar1.add(menu_cadastrar);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/zoom.png"))); // NOI18N
        jMenu3.setText("Pesquisar");

        menu_pesquisarImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/casa1.png"))); // NOI18N
        menu_pesquisarImovel.setText("Imóveis");
        menu_pesquisarImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pesquisarImovelActionPerformed(evt);
            }
        });
        jMenu3.add(menu_pesquisarImovel);

        menu_pesquisarClienteDono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        menu_pesquisarClienteDono.setText("Clientes/Donos");
        menu_pesquisarClienteDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pesquisarClienteDonoActionPerformed(evt);
            }
        });
        jMenu3.add(menu_pesquisarClienteDono);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dinheiro1.png"))); // NOI18N
        jMenu4.setText("Financeiro");
        jMenuBar1.add(jMenu4);
        jMenuBar1.add(jMenu2);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/information.png"))); // NOI18N
        jMenu1.setText("Sobre");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_cadastrarDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadastrarDonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_cadastrarDonoActionPerformed

    private void menu_cadastrarImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadastrarImovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_cadastrarImovelActionPerformed

    private void menu_cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadastrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_cadastrarClienteActionPerformed

    private void menu_pesquisarClienteDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pesquisarClienteDonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_pesquisarClienteDonoActionPerformed

    private void menu_pesquisarImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pesquisarImovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_pesquisarImovelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu_cadastrar;
    private javax.swing.JMenuItem menu_cadastrarCliente;
    private javax.swing.JMenuItem menu_cadastrarDono;
    private javax.swing.JMenuItem menu_cadastrarImovel;
    private javax.swing.JMenuItem menu_pesquisarClienteDono;
    private javax.swing.JMenuItem menu_pesquisarImovel;
    // End of variables declaration//GEN-END:variables
}
